name: Run Dengue Data Script Daily

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC
  workflow_dispatch:     # Allows manual trigger from the Actions tab

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas matplotlib geopandas shapely folium plotly pytz scikit-learn joblib seaborn

      - name: Run Daily Data Processing Script
        run: python dailydenguedataprocessing.py

      - name: Train ML Models
        run: python dengue_ml_models_improved.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add *.csv *.pkl *.json *.png
          git commit -m "Daily update: data processing and ML model training" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}
